### ISSUE TITLE
Aggregate does not fail gracefully when a timeout happens

### ISSUE THREAD

**Issue by samstorment** [redis/NRedisStack#245] opened 2024-02-12 22:37 UTC
# Quick Description

When running `ft.Aggregate` or `ft.AggregateAsync` and the aggregate takes longer than the timeout set by `TIMEOUT` from `FT.CONFIG`, there is no obvious indication of a timeout which causes some unexpected null references.

## Versions

**NRedisStack Version**: 0.11.0

**Redis Stack Version**: I'm using the redis/redis-stack:latest docker image. Running `redis-cli -v` shows redis version 6.2.11

## More Details 

I have an aggregate that looks like the below on a database with over 2 million key/values of JSON. The `@address` index is a text field and all the data is related to properties in the city of Chicago. This means a query term like `"chicago"` takes a pretty decent chunk of time since almost all records include chicago, causing a timeout.

```csharp
var req = new AggregationRequest("@address:chicago")
    .GroupBy("@houseNumber", Reducers.Max("@year").As("maxYear"), Reducers.Min("@year").As("minYear"))
    .Limit(0, 25);

var aggResult = ft.Aggregate("idx:search", req);
```

When I go to read the rows of my aggregation result, the underlying dictionary within the row class is null and a `System.NullReferenceException` is thrown. Upping the `TIMEOUT` config setting from the default 500ms to a higher value like 5000ms using `FT.CONFIG SET TIMEOUT 5000` does fix the issue since the timeout no longer happens, but it took me a fair bit of digging to understand that would fix things.

```csharp
// aggResults.TotalResults is reported as ~900,000 here. It varies based on how much work was done before the timeout
for (var i = 0; i < 25; i++) {
      var row = aggResult.GetRow(i);

      // the underlying dictionary of the Row is null here, 
      // causing a null reference exception when trying to access `row["houseNumber"]`
      var houseNumber = row["houseNumber"];
}
```

I'm wondering if there's a way to know an aggregation timed out to prevent the null reference exception. When I run the aggregation in the redis-cli and it times out, it returns the number of total results and an empty list, but there's no obvious indication that a time out happened.

```bash
> FT.AGGREGATE idx:search "(@address:chicago)" GROUPBY 1 @houseNumber REDUCE max 1 @year as maxYear REDUCE min 1 @year as minYear
1) "871299"
2) (empty list or set)
```

**Comment by shacharPash** [comment] 2024-03-03 10:29
Hey @samstorment , I tried to reproduce your error in order to understand what causes the issue, but I actually received a timeout message.

I wrote this test:
```csharp
  [Fact]
  public void AggregateShouldFailGracefullyOnTimeout()
  {
      IDatabase db = redisFixture.Redis.GetDatabase();
      db.Execute("FLUSHALL");
      var ft = db.FT();

      // create an index:
      Schema schema = new Schema()
                              .AddTextField("address")
                              .AddTextField("houseNumber")
                              .AddNumericField("year");
      ft.Create(index, FTCreateParams.CreateParams(), schema);

      SetupLargeDatasetForTimeout(db);

      // Create the aggregation request
      var req = new AggregationRequest("@address:chicago")
          .GroupBy("@houseNumber", Reducers.Max("@year").As("maxYear"), Reducers.Min("@year").As("minYear"))
          .Limit(0, 25);

      var aggResult = ft.Aggregate(index, req);
  }

  private void SetupLargeDatasetForTimeout(IDatabase db)
  {
      for (int i = 0; i < 2000000; i++)
      {
          var docId = $"doc{i}";
          db.HashSet(docId, new HashEntry[]
          {
              new HashEntry("address", "chicago"),
              new HashEntry("houseNumber", i.ToString()),
              new HashEntry("year", 2000 + (i % 20)) // Simple data, adjust as needed
          });
      }
  }
```
I debug the test and got this message:
![Screenshot 2024-03-03 at 12 01 08](https://github.com/redis/NRedisStack/assets/93581407/40b0b6b3-a953-46d3-9ad5-27360e08e48f)

when I wrote the Aggregation in redis-cli I got this:
```bash
127.0.0.1:6379> “FT.AGGREGATE” “TEST_INDEX” “@address:chicago” “GROUPBY” “1” “@houseNumber” “REDUCE” “MAX” “1” “@year” “AS” “maxYear” “REDUCE” “MIN” “1” “@year” “AS” “minYear” “LIMIT” “0" “25”
1) Timeout limit was reached
```

I would appreciate it if you could explain to me what I did differently from you so that we can understand what the problem is in your case.

**Comment by shacharPash** [comment] 2024-03-07 11:25
@samstorment , did you see my comment?
I will be happy to help you and fix what is needed / close the issue if the problem is solved.

**Comment by samstorment** [comment] 2024-03-07 16:20
@shacharPash Sorry I've had a really busy week and haven't had a chance to properly dig into yet. I'll have free time this weekend and revisit my code along with your comment and try to get you a reproducible version of my issue.

**Comment by samstorment** [comment] 2024-03-09 23:34
@shacharPash I've figured out the issue. It's to do with the [ON_TIMEOUT FT.CONFIG setting](https://redis.io/docs/interact/search-and-query/basic-constructs/configuration-parameters/#on_timeout). For me, this was set to "return" by default:

```bash
> FT.CONFIG GET ON_TIMEOUT
1) 1) "ON_TIMEOUT"
   2) "return"
```

This made it so my aggregate would silently return whatever subset of results it had accumulated. If I changed this setting to "fail", I received the same error messages as you.

```bash
> FT.CONFIG SET ON_TIMEOUT fail
"OK"
```

Honestly I'm not sure whether I'm misusing NRedisStack by looping through the `aggResult` the way I am, or if NRedisStack doesn't handle `ON_TIMEOUT return` properly.

**Comment by shacharPash** [comment] 2024-03-12 09:50
Hi, it seems to me that the behavior actually makes sense, when you change to fail do you get what you wanted in the first place?

**Comment by samstorment** [comment] 2024-03-14 03:58
@shacharPash Yeah changing to fail makes things work as expected. I will say that with limited context I have from the description of the `RETURN` policy, I was thinking that it would still work to call `aggResult.getRow()` up to `aggResult.TotalResults` times and the underlying dictionary wouldn't be null. I'm certainly no redis expert though so I might just be misunderstanding this.

> RETURN: this policy will return the top results accumulated by the query until it timed out.

**Comment by shacharPash** [comment] 2024-03-19 07:55
Hi, I understand that there is no change that needs to be made in NRedisStack, so I am closing its profile, if you disagree with me, write to me.

**Closed by shacharPash** 2024-03-19 07:55 UTC
